// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfjbiegkkjdswvujscdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mamJpZWdra2pkc3d2dWpzY2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzM4MzEsImV4cCI6MjA3MDE0OTgzMX0.xXYpKI-iYF_Ljbqb9YwK5u2j3YBbeEGObrPY42rEYHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});